### ISSUE TITLE
Not able to retrain a locally stored model

### ISSUE THREAD

**Issue by rajamanthan** [MauryaRitesh/Facial-Expression-Detection#10]
I have a trained model stored in my local storage. My model can recognise a person. I want to retrain it to detect expression of that person. How can I use your code to do so? Please help!

**Comment by MauryaRitesh** [comment]
You need to a dataset of facial images contained label-wise in several directories. Then just run the retrain.py program. For more detailed info. watch the video: https://youtu.be/Dqa-3N8VZbw
