### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'app'

### ISSUE THREAD

**Issue by rijalxp** [MauryaRitesh/Facial-Expression-Detection#11]
can you help for this problem?
![Capture](https://user-images.githubusercontent.com/6286434/67859983-6fe86480-fb4f-11e9-8a8b-2cf2586ce35f.PNG)

**Comment by quicktwit** [comment]
Which tensorflow are you using?

**Comment by RichHillman** [comment]
I got this problem, too. tensorflow==2.1.0 macOS catalina
