### ISSUE TITLE
error while executing terminal command

### ISSUE THREAD

**Issue by bangonuniverse** [MauryaRitesh/Facial-Expression-Detection#12]
it is showing error while i am executing this cmnd in cmd prompt
python retrain.py --output_graph=retrained_graph.pb --output_labels=retrained_labels.txt --architecture=MobileNet_1.0_224 --image_dir=images
Error :-   File "retrain.py", line 234, in get_image_path
    mod_index = index % len(category_list)
ZeroDivisionError: integer division or modulo by zer

**Comment by MauryaRitesh** [comment]
You should check the image directory. It seems like no image is present in the given directory, therefore the number of images = 0 hence you're getting this error.
