### ISSUE TITLE
Create a Colab notebook

### ISSUE THREAD

**Issue by MauryaRitesh** [MauryaRitesh/Facial-Expression-Detection#17]
Provide a Colab notebook for faster implementation.

**Comment by NevilleMthw** [comment]
Do you want a Colab notebook created?

**Comment by MauryaRitesh** [comment]
Yes

**Comment by NevilleMthw** [comment]
Do you want any content in it or just empty?

**Comment by Aragorn-64** [comment]
Hi @MauryaRitesh, I am learning/using Colab as part of my Intro to Data Science course in college. I liked the idea behind the project and want to try and contribute to it. I can try and make a Colab notebook for this project as I also think it will lead to smoother usage. Can you assign this task to me?

**Comment by donheshanthaka** [comment]
Hey can you assign me to this issue as well. I do have experience working with Colab notebooks for my own projects.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by Bhargav-44** [comment]
@MauryaRitesh does this issue still needs to be worked one...if yes can u assign it to me??
