### ISSUE TITLE
face_crop.py it is not doing anything

### ISSUE THREAD

**Issue by ramendrapathak** [MauryaRitesh/Facial-Expression-Detection#4]
Ramendra Pathak

Is there any specific (size or gray) kind of images i need to download or any image will work.
As when m running the face_crop.py it is not doing anything with no error in the console.

i have just downloaded the normal images from google just by writing "happy person face images hd"

Please revert ASAP﻿

this is console...........................:

Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 18:50:55) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.2.0 -- An enhanced Interactive Python.

runfile('D:/python/my code/face_crop.py', wdir='D:/python/my code')
0
1
2
3
4﻿

**Comment by ramendrapathak** [comment]
C:\Users\Ramendra\Desktop\my code>face_crop.py
  File "C:\Users\Ramendra\Desktop\my code\face_crop.py", line 14
    directory = "C:\Users\Ramendra\Desktop\my code\images"
               ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Comment by MauryaRitesh** [comment]
It is advisable to use single type of entire images, that is use only colour images or only grey scale images. Also, cropping all the images to a specific size like 512 × 512 will eventually increase accuracy.

**Comment by ShifaMYS** [comment]
I did everything accordingly yet it's not working!
