### ISSUE TITLE
error

### ISSUE THREAD

**Issue by srilekhapamarthi** [MauryaRitesh/Facial-Expression-Detection#5]
I'm getting an error that when i'm running "label.py" code it is showing as there is no module found "retrained_graph.pb".
How can i solve that error?  Can you please help me out with that.
Thank you

**Comment by MauryaRitesh** [comment]
@srilekhapamarthi  You need to **retrain** the model before using the **label.py** program.  There is another program named **retrain.py** which you need to run with proper set of data as explained in the video: https://youtu.be/Dqa-3N8VZbw
Also, don't forget to follow the Steps as suggested in this repository.
