### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Angshuman1997** [MauryaRitesh/Facial-Expression-Detection#7]
Traceback (most recent call last):
  File "C:/Users/Angshuman Bardhan/Desktop/exp.py", line 1, in <module>
    import matplotlib.pylab as plt
ModuleNotFoundError: No module named 'matplotlib'

**Comment by MauryaRitesh** [comment]
It seems like you don't have Matplotlib installed on your system. You need to install it for getting rid of the error.
To do so hit the following in your Command Prompt:
pip install matplotlib
